(cl:defpackage gazebo_plugins_local-srv
  (:use )
  (:export
   "GAZEBOGETBOUNDINGBOXES"
   "<GAZEBOGETBOUNDINGBOXES-REQUEST>"
   "GAZEBOGETBOUNDINGBOXES-REQUEST"
   "<GAZEBOGETBOUNDINGBOXES-RESPONSE>"
   "GAZEBOGETBOUNDINGBOXES-RESPONSE"
   "GAZEBOGETJOINTSAXES"
   "<GAZEBOGETJOINTSAXES-REQUEST>"
   "GAZEBOGETJOINTSAXES-REQUEST"
   "<GAZEBOGETJOINTSAXES-RESPONSE>"
   "GAZEBOGETJOINTSAXES-RESPONSE"
  ))

