controller_manager:
  ros__parameters:
    update_rate: 250
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    hand_controller:
      type: position_controllers/GripperActionController

arm_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    command_interfaces: [position]
    state_interfaces: [position, velocity]

hand_controller:
  ros__parameters:
    joint: panda_finger_joint1   # adjust if your model uses different names
