// Generated by gencpp from file grasp_detection/BoundingBox2DArray.msg
// DO NOT EDIT!


#ifndef GRASP_DETECTION_MESSAGE_BOUNDINGBOX2DARRAY_H
#define GRASP_DETECTION_MESSAGE_BOUNDINGBOX2DARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <grasp_detection/BoundingBox2D.h>

namespace grasp_detection
{
template <class ContainerAllocator>
struct BoundingBox2DArray_
{
  typedef BoundingBox2DArray_<ContainerAllocator> Type;

  BoundingBox2DArray_()
    : header()
    , detections()  {
    }
  BoundingBox2DArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::grasp_detection::BoundingBox2D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::grasp_detection::BoundingBox2D_<ContainerAllocator> >> _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::grasp_detection::BoundingBox2DArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grasp_detection::BoundingBox2DArray_<ContainerAllocator> const> ConstPtr;

}; // struct BoundingBox2DArray_

typedef ::grasp_detection::BoundingBox2DArray_<std::allocator<void> > BoundingBox2DArray;

typedef boost::shared_ptr< ::grasp_detection::BoundingBox2DArray > BoundingBox2DArrayPtr;
typedef boost::shared_ptr< ::grasp_detection::BoundingBox2DArray const> BoundingBox2DArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grasp_detection::BoundingBox2DArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grasp_detection::BoundingBox2DArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grasp_detection::BoundingBox2DArray_<ContainerAllocator1> & lhs, const ::grasp_detection::BoundingBox2DArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grasp_detection::BoundingBox2DArray_<ContainerAllocator1> & lhs, const ::grasp_detection::BoundingBox2DArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grasp_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::grasp_detection::BoundingBox2DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasp_detection::BoundingBox2DArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grasp_detection::BoundingBox2DArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grasp_detection::BoundingBox2DArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_detection::BoundingBox2DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_detection::BoundingBox2DArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grasp_detection::BoundingBox2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8808fd7ac6a4a8b8ea412f6bc79036f7";
  }

  static const char* value(const ::grasp_detection::BoundingBox2DArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8808fd7ac6a4a8b8ULL;
  static const uint64_t static_value2 = 0xea412f6bc79036f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::grasp_detection::BoundingBox2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grasp_detection/BoundingBox2DArray";
  }

  static const char* value(const ::grasp_detection::BoundingBox2DArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grasp_detection::BoundingBox2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message contains array of BoundingBox2D messages \n"
"\n"
"std_msgs/Header header\n"
"\n"
"BoundingBox2D[] detections\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: grasp_detection/BoundingBox2D\n"
"# The message defines the 2D bounding box of a certain object in the image.\n"
"\n"
"# ID or label of the detected object\n"
"string object_id\n"
"\n"
"# 2D coordinatses of the bounding box in the image plane\n"
"int32 x_min\n"
"int32 y_min\n"
"int32 x_max\n"
"int32 y_max\n"
;
  }

  static const char* value(const ::grasp_detection::BoundingBox2DArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grasp_detection::BoundingBox2DArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoundingBox2DArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grasp_detection::BoundingBox2DArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grasp_detection::BoundingBox2DArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "detections: ";
    if (v.detections.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::grasp_detection::BoundingBox2D_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.detections[i]);
    }
    if (v.detections.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASP_DETECTION_MESSAGE_BOUNDINGBOX2DARRAY_H
