// Generated by gencpp from file grasp_detection/BoundingBox3DArray.msg
// DO NOT EDIT!


#ifndef GRASP_DETECTION_MESSAGE_BOUNDINGBOX3DARRAY_H
#define GRASP_DETECTION_MESSAGE_BOUNDINGBOX3DARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <grasp_detection/BoundingBox3D.h>

namespace grasp_detection
{
template <class ContainerAllocator>
struct BoundingBox3DArray_
{
  typedef BoundingBox3DArray_<ContainerAllocator> Type;

  BoundingBox3DArray_()
    : header()
    , bboxes_3d()  {
    }
  BoundingBox3DArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , bboxes_3d(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::grasp_detection::BoundingBox3D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::grasp_detection::BoundingBox3D_<ContainerAllocator> >> _bboxes_3d_type;
  _bboxes_3d_type bboxes_3d;





  typedef boost::shared_ptr< ::grasp_detection::BoundingBox3DArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grasp_detection::BoundingBox3DArray_<ContainerAllocator> const> ConstPtr;

}; // struct BoundingBox3DArray_

typedef ::grasp_detection::BoundingBox3DArray_<std::allocator<void> > BoundingBox3DArray;

typedef boost::shared_ptr< ::grasp_detection::BoundingBox3DArray > BoundingBox3DArrayPtr;
typedef boost::shared_ptr< ::grasp_detection::BoundingBox3DArray const> BoundingBox3DArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grasp_detection::BoundingBox3DArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grasp_detection::BoundingBox3DArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grasp_detection::BoundingBox3DArray_<ContainerAllocator1> & lhs, const ::grasp_detection::BoundingBox3DArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.bboxes_3d == rhs.bboxes_3d;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grasp_detection::BoundingBox3DArray_<ContainerAllocator1> & lhs, const ::grasp_detection::BoundingBox3DArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grasp_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::grasp_detection::BoundingBox3DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasp_detection::BoundingBox3DArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grasp_detection::BoundingBox3DArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grasp_detection::BoundingBox3DArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_detection::BoundingBox3DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_detection::BoundingBox3DArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grasp_detection::BoundingBox3DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "972964bfa630ec8002b6b6713451b7e5";
  }

  static const char* value(const ::grasp_detection::BoundingBox3DArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x972964bfa630ec80ULL;
  static const uint64_t static_value2 = 0x02b6b6713451b7e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::grasp_detection::BoundingBox3DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grasp_detection/BoundingBox3DArray";
  }

  static const char* value(const ::grasp_detection::BoundingBox3DArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grasp_detection::BoundingBox3DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message contains array of BoundingBox3D messages \n"
"\n"
"std_msgs/Header header\n"
"\n"
"BoundingBox3D[] bboxes_3d\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: grasp_detection/BoundingBox3D\n"
"# A 3D bounding box that can be positioned and rotated about its center (6 DOF)\n"
"# Dimensions of this box are in meters\n"
"\n"
"# ID or label of the detected object\n"
"string object_id\n"
"\n"
"# The 3D position and orientation of the bounding box center\n"
"geometry_msgs/Pose center\n"
"\n"
"# The size of the bounding box, in meters, surrounding the object's center\n"
"geometry_msgs/Vector3 size\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::grasp_detection::BoundingBox3DArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grasp_detection::BoundingBox3DArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.bboxes_3d);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoundingBox3DArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grasp_detection::BoundingBox3DArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grasp_detection::BoundingBox3DArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bboxes_3d: ";
    if (v.bboxes_3d.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.bboxes_3d.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::grasp_detection::BoundingBox3D_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.bboxes_3d[i]);
    }
    if (v.bboxes_3d.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASP_DETECTION_MESSAGE_BOUNDINGBOX3DARRAY_H
