// Generated by gencpp from file grasp_detection/DetectGrasps.msg
// DO NOT EDIT!


#ifndef GRASP_DETECTION_MESSAGE_DETECTGRASPS_H
#define GRASP_DETECTION_MESSAGE_DETECTGRASPS_H

#include <ros/service_traits.h>


#include <grasp_detection/DetectGraspsRequest.h>
#include <grasp_detection/DetectGraspsResponse.h>


namespace grasp_detection
{

struct DetectGrasps
{

typedef DetectGraspsRequest Request;
typedef DetectGraspsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DetectGrasps
} // namespace grasp_detection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::grasp_detection::DetectGrasps > {
  static const char* value()
  {
    return "7b96d74daf2ef22069cf549130b286e1";
  }

  static const char* value(const ::grasp_detection::DetectGrasps&) { return value(); }
};

template<>
struct DataType< ::grasp_detection::DetectGrasps > {
  static const char* value()
  {
    return "grasp_detection/DetectGrasps";
  }

  static const char* value(const ::grasp_detection::DetectGrasps&) { return value(); }
};


// service_traits::MD5Sum< ::grasp_detection::DetectGraspsRequest> should match
// service_traits::MD5Sum< ::grasp_detection::DetectGrasps >
template<>
struct MD5Sum< ::grasp_detection::DetectGraspsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::grasp_detection::DetectGrasps >::value();
  }
  static const char* value(const ::grasp_detection::DetectGraspsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::grasp_detection::DetectGraspsRequest> should match
// service_traits::DataType< ::grasp_detection::DetectGrasps >
template<>
struct DataType< ::grasp_detection::DetectGraspsRequest>
{
  static const char* value()
  {
    return DataType< ::grasp_detection::DetectGrasps >::value();
  }
  static const char* value(const ::grasp_detection::DetectGraspsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::grasp_detection::DetectGraspsResponse> should match
// service_traits::MD5Sum< ::grasp_detection::DetectGrasps >
template<>
struct MD5Sum< ::grasp_detection::DetectGraspsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::grasp_detection::DetectGrasps >::value();
  }
  static const char* value(const ::grasp_detection::DetectGraspsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::grasp_detection::DetectGraspsResponse> should match
// service_traits::DataType< ::grasp_detection::DetectGrasps >
template<>
struct DataType< ::grasp_detection::DetectGraspsResponse>
{
  static const char* value()
  {
    return DataType< ::grasp_detection::DetectGrasps >::value();
  }
  static const char* value(const ::grasp_detection::DetectGraspsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRASP_DETECTION_MESSAGE_DETECTGRASPS_H
