// Generated by gencpp from file gazebo_plugins_local/GazeboGetBoundingBoxesRequest.msg
// DO NOT EDIT!


#ifndef GAZEBO_PLUGINS_LOCAL_MESSAGE_GAZEBOGETBOUNDINGBOXESREQUEST_H
#define GAZEBO_PLUGINS_LOCAL_MESSAGE_GAZEBOGETBOUNDINGBOXESREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gazebo_plugins_local
{
template <class ContainerAllocator>
struct GazeboGetBoundingBoxesRequest_
{
  typedef GazeboGetBoundingBoxesRequest_<ContainerAllocator> Type;

  GazeboGetBoundingBoxesRequest_()
    {
    }
  GazeboGetBoundingBoxesRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GazeboGetBoundingBoxesRequest_

typedef ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest_<std::allocator<void> > GazeboGetBoundingBoxesRequest;

typedef boost::shared_ptr< ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest > GazeboGetBoundingBoxesRequestPtr;
typedef boost::shared_ptr< ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest const> GazeboGetBoundingBoxesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace gazebo_plugins_local

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_plugins_local/GazeboGetBoundingBoxesRequest";
  }

  static const char* value(const ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GazeboGetBoundingBoxesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_PLUGINS_LOCAL_MESSAGE_GAZEBOGETBOUNDINGBOXESREQUEST_H
