// Generated by gencpp from file gazebo_plugins_local/GazeboGetJointsAxes.msg
// DO NOT EDIT!


#ifndef GAZEBO_PLUGINS_LOCAL_MESSAGE_GAZEBOGETJOINTSAXES_H
#define GAZEBO_PLUGINS_LOCAL_MESSAGE_GAZEBOGETJOINTSAXES_H

#include <ros/service_traits.h>


#include <gazebo_plugins_local/GazeboGetJointsAxesRequest.h>
#include <gazebo_plugins_local/GazeboGetJointsAxesResponse.h>


namespace gazebo_plugins_local
{

struct GazeboGetJointsAxes
{

typedef GazeboGetJointsAxesRequest Request;
typedef GazeboGetJointsAxesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GazeboGetJointsAxes
} // namespace gazebo_plugins_local


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_plugins_local::GazeboGetJointsAxes > {
  static const char* value()
  {
    return "7e7fae98615461e70f83b405c6a2a27b";
  }

  static const char* value(const ::gazebo_plugins_local::GazeboGetJointsAxes&) { return value(); }
};

template<>
struct DataType< ::gazebo_plugins_local::GazeboGetJointsAxes > {
  static const char* value()
  {
    return "gazebo_plugins_local/GazeboGetJointsAxes";
  }

  static const char* value(const ::gazebo_plugins_local::GazeboGetJointsAxes&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_plugins_local::GazeboGetJointsAxesRequest> should match
// service_traits::MD5Sum< ::gazebo_plugins_local::GazeboGetJointsAxes >
template<>
struct MD5Sum< ::gazebo_plugins_local::GazeboGetJointsAxesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_plugins_local::GazeboGetJointsAxes >::value();
  }
  static const char* value(const ::gazebo_plugins_local::GazeboGetJointsAxesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_plugins_local::GazeboGetJointsAxesRequest> should match
// service_traits::DataType< ::gazebo_plugins_local::GazeboGetJointsAxes >
template<>
struct DataType< ::gazebo_plugins_local::GazeboGetJointsAxesRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_plugins_local::GazeboGetJointsAxes >::value();
  }
  static const char* value(const ::gazebo_plugins_local::GazeboGetJointsAxesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_plugins_local::GazeboGetJointsAxesResponse> should match
// service_traits::MD5Sum< ::gazebo_plugins_local::GazeboGetJointsAxes >
template<>
struct MD5Sum< ::gazebo_plugins_local::GazeboGetJointsAxesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_plugins_local::GazeboGetJointsAxes >::value();
  }
  static const char* value(const ::gazebo_plugins_local::GazeboGetJointsAxesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_plugins_local::GazeboGetJointsAxesResponse> should match
// service_traits::DataType< ::gazebo_plugins_local::GazeboGetJointsAxes >
template<>
struct DataType< ::gazebo_plugins_local::GazeboGetJointsAxesResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_plugins_local::GazeboGetJointsAxes >::value();
  }
  static const char* value(const ::gazebo_plugins_local::GazeboGetJointsAxesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_PLUGINS_LOCAL_MESSAGE_GAZEBOGETJOINTSAXES_H
