// Generated by gencpp from file gazebo_plugins_local/GazeboGetBoundingBoxes.msg
// DO NOT EDIT!


#ifndef GAZEBO_PLUGINS_LOCAL_MESSAGE_GAZEBOGETBOUNDINGBOXES_H
#define GAZEBO_PLUGINS_LOCAL_MESSAGE_GAZEBOGETBOUNDINGBOXES_H

#include <ros/service_traits.h>


#include <gazebo_plugins_local/GazeboGetBoundingBoxesRequest.h>
#include <gazebo_plugins_local/GazeboGetBoundingBoxesResponse.h>


namespace gazebo_plugins_local
{

struct GazeboGetBoundingBoxes
{

typedef GazeboGetBoundingBoxesRequest Request;
typedef GazeboGetBoundingBoxesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GazeboGetBoundingBoxes
} // namespace gazebo_plugins_local


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_plugins_local::GazeboGetBoundingBoxes > {
  static const char* value()
  {
    return "4a5148ef6b2e02f98aaa72ae4f26020a";
  }

  static const char* value(const ::gazebo_plugins_local::GazeboGetBoundingBoxes&) { return value(); }
};

template<>
struct DataType< ::gazebo_plugins_local::GazeboGetBoundingBoxes > {
  static const char* value()
  {
    return "gazebo_plugins_local/GazeboGetBoundingBoxes";
  }

  static const char* value(const ::gazebo_plugins_local::GazeboGetBoundingBoxes&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest> should match
// service_traits::MD5Sum< ::gazebo_plugins_local::GazeboGetBoundingBoxes >
template<>
struct MD5Sum< ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_plugins_local::GazeboGetBoundingBoxes >::value();
  }
  static const char* value(const ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest> should match
// service_traits::DataType< ::gazebo_plugins_local::GazeboGetBoundingBoxes >
template<>
struct DataType< ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_plugins_local::GazeboGetBoundingBoxes >::value();
  }
  static const char* value(const ::gazebo_plugins_local::GazeboGetBoundingBoxesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_plugins_local::GazeboGetBoundingBoxesResponse> should match
// service_traits::MD5Sum< ::gazebo_plugins_local::GazeboGetBoundingBoxes >
template<>
struct MD5Sum< ::gazebo_plugins_local::GazeboGetBoundingBoxesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_plugins_local::GazeboGetBoundingBoxes >::value();
  }
  static const char* value(const ::gazebo_plugins_local::GazeboGetBoundingBoxesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_plugins_local::GazeboGetBoundingBoxesResponse> should match
// service_traits::DataType< ::gazebo_plugins_local::GazeboGetBoundingBoxes >
template<>
struct DataType< ::gazebo_plugins_local::GazeboGetBoundingBoxesResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_plugins_local::GazeboGetBoundingBoxes >::value();
  }
  static const char* value(const ::gazebo_plugins_local::GazeboGetBoundingBoxesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_PLUGINS_LOCAL_MESSAGE_GAZEBOGETBOUNDINGBOXES_H
