controller_manager:
  ros__parameters:
    update_rate: 200

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_trajectory_controller:
  ros__parameters:
    # 7-DOF arm only (no gripper) for trajectory control
    joints: [
      panda_joint1, panda_joint2, panda_joint3,
      panda_joint4, panda_joint5, panda_joint6, panda_joint7
    ]
    command_interfaces: [position]
    state_interfaces: [position]
    allow_partial_joints_goal: false
    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.01
      panda_joint1: {trajectory: 0.05, goal: 0.01}
      panda_joint2: {trajectory: 0.05, goal: 0.01}
      panda_joint3: {trajectory: 0.05, goal: 0.01}
      panda_joint4: {trajectory: 0.05, goal: 0.01}
      panda_joint5: {trajectory: 0.05, goal: 0.01}
      panda_joint6: {trajectory: 0.05, goal: 0.01}
      panda_joint7: {trajectory: 0.05, goal: 0.01}
