(cl:defpackage grasp_detection-msg
  (:use )
  (:export
   "<BOUNDINGBOX2D>"
   "BOUNDINGBOX2D"
   "<BOUNDINGBOX2DARRAY>"
   "BOUNDINGBOX2DARRAY"
   "<BOUNDINGBOX3D>"
   "BOUNDINGBOX3D"
   "<BOUNDINGBOX3DARRAY>"
   "BOUNDINGBOX3DARRAY"
   "<GRASP>"
   "GRASP"
   "<PERCEPTION>"
   "PERCEPTION"
   "<PERCEPTIONSINGLECAMERA>"
   "PERCEPTIONSINGLECAMERA"
  ))

